# Site
repository: jane-mys.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jane (Mengyi) Shi
title: Education Leader & Project Manager
email: mengyishi9@gmail.com
website: jane-mys.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: Jane-MYS
linkedin_username: jane-shi-m-a-pmp-46a418153
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 
  icon: 
  url: 
# - title:
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Empowering Learning Through Innovation
about_profile_image: images/profile.jpg
about_content: |
  I'm an Ed.D. candidate at Northeastern University and a Program Coordinator at Santa Monica College, where I lead tutoring programs for over 35 student workers each semester.

  My work spans across educational leadership, EdTech implementation, and volunteer project management. I've developed virtual platforms for tutoring, founded TransferBot – an AI-powered chatbot for California transfer students – and created apps and sites to help people make smarter financial and educational decisions.

  I hold a PMP certification, and I'm passionate about optimizing workflows, mentoring student success, and expanding access to learning, both in person and online.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Education Leadership
        sub_title: Santa Monica College
        caption: Program Coordinator
        description: |
          - Scaled tutoring across all modern languages
          - Supervised 35+ tutors per term
          - Developed online learning platform with 2,000+ users

      - layout: left
        title: EdTech & Project Management
        sub_title: TransferBot
        caption: Founder & Developer
        description: |
          - Built AI academic advising bot on Discord
          - Automated personalized transfer pathways for UC/CSU
          - PMI (Project Manager) serving 4,000+ members
          - Integrated Mailchimp, Google Workspace, and AI tools

      - layout: left
        title: Global Education & Teaching
        sub_title: Capital University of PE & Sports
        caption: Assistant Manager, International Ed.
        description: |
          - Designed training for global students (95% satisfaction)
          - Tracked outcomes with analytics tools
          - ESL Instructor roles across LATTC, LSI, Easyke

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: TransferBot
        sub_title: Academic AI Chatbot
        description: |
          Built for California community college students to navigate the transfer system using Discord AI.
          - Automated transfer pathway recommendations
          - Personalized academic advising
          - Integrated with UC/CSU systems

      - layout: top-middle
        title: Virtual Tutoring Hub
        sub_title: Santa Monica College
        description: |
          Designed and launched an online platform for Santa Monica College tutors:
          - Increased access to tutoring services
          - Streamlined session booking
          - Enhanced student-tutor communication

      - layout: top-middle
        title: Credit Card Rewards App
        description: |
          Designed a consumer finance tool that compares rewards and perks:
          - User-friendly interface
          - Real-time comparison features
          - Personalized recommendations

  - title: Research & Development
    layout: text
    content: |
      ### Doctoral Research
      - **Northeastern University** - Ed.D. Candidate
      - Exploring equity-centered design in hybrid tutoring services
      - Conducting action research with faculty and students

      ### Certifications
      - PMP – Project Management Institute
      - Google Project Management
      - DEI Leadership – Rice University
      - Business Analytics – Rice University

      ### Professional Involvement
      - Board Member – APIDA Steering Committee
      - Contributing to campus DEI strategy and advocacy efforts

  - title: Contact
    layout: text
    content: |
      Interested in collaborating or hiring me? Let's connect!

      [Download Resume](path/to/resume.pdf) | [LinkedIn](https://linkedin.com/in/jane-shi-m-a-pmp-46a418153) | [GitHub](https://github.com/Jane-MYS)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
